"""
Django settings for CNC_consultant project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from dotenv import load_dotenv
import os
load_dotenv()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.main.apps.MainConfig',
    'apps.accounts.apps.AccountsConfig',    
    "apps.wikigcode.apps.WikigcodeConfig",
    "apps.worklogs.apps.WorklogsConfig",
    "apps.calculator.apps.CalculatorConfig",
    # 'apps.calculator',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CNC_consultant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # context_processors содержит список путей к вызываемым объектам, которые возвращают словарь для объединения с контекстом каждого представления, избавляя нас от необходимости добавлять одни и те же данные снова и снова.
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'CNC_consultant.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ru'
TIME_ZONE = 'Europe/Moscow' 

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Пути к папкам со статическими файлами (если используете дополнительные папки)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Папка static в корне проекта
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # для collectstatic при деплое

MEDIA_ROOT = (BASE_DIR / 'media')   # полный путь к каталогу, в котором хранятся загруженные файлы
MEDIA_URL = '/media/'   # базовый URL-адрес для обслуживания медиафайлов

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = "/"
# LOGOUT_REDIRECT_URL = "/" #  сделан для того, чтобы не создавать дополнительную страницу, которая будет отображаться после выхода пользователя, а сразу выполнить редирект на главную страницу сайта
# для пользователей, которые установят флажок "Remember me:", сеанс будет длиться до тех пор, пока  не истечёт время (в секундах), заданное в параметре 
# По умолчанию сессия у Django хранится 2 недели, то есть после авторизации в течение 2х недель мы можем заходить на сайт, и нам не потребуется авторизация на нем. А мы реализуем следующую логику, например если мы хотим, чтобы после закрытия страницы сайта, наша авторизация обнулялась, и нам придется каждый раз проходить авторизацию на сайте, то мы можем не устанавливать галочку у поля "Remember me".
SESSION_COOKIE_AGE = 60 * 60 * 24 *  30     # 30 дней

LOGIN_URL = '/apps/accounts/login/'


AUTHENTICATION_BACKENDS = (
    # Cерверные части Google, GitHub, Yandex
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.yandex.YandexOAuth2',  
    'django.contrib.auth.backends.ModelBackend',    # базовая серверная часть аутентификации, которая по умолчанию входит в Django,
)




# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# Конфигурации социальной аутентификации для GitHub
SOCIAL_AUTH_GITHUB_KEY = os.getenv('GITHUB_KEY')
SOCIAL_AUTH_GITHUB_SECRET = os.getenv('GITHUB_SECRET')

# Конфигурации социальной аутентификации для Google
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('GOOGLE_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('GOOGLE_SECRET')

# Конфигурации социальной аутентификации для Yandex
SOCIAL_AUTH_YANDEX_OAUTH2_KEY = os.getenv('YANDEX_KEY')
SOCIAL_AUTH_YANDEX_OAUTH2_SECRET = os.getenv('YANDEX_SECRET')