# Generated by Django 5.2.4 on 2025-07-09 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('job_title', models.CharField(blank=True, max_length=50, verbose_name='Должность')),
                ('info_about_yourself', models.TextField(blank=True, max_length=500, verbose_name='Информация о себе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Инфо профиля',
                'verbose_name_plural': 'Инфо профилей',
            },
        ),
    ]
