# Generated by Django 5.2.4 on 2025-07-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikigcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ('birth_date',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='info',
            name='birth_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
