# Generated by Django 5.2.4 on 2025-07-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikigcode', '0002_alter_info_options_info_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ('publication_date',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='info',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='info',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='info',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='info',
            name='title',
            field=models.CharField(default='Статья', max_length=100),
        ),
    ]
