# Generated by Django 5.2.4 on 2025-07-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('work_time_start', models.DateField()),
                ('work_time_end', models.DateField()),
                ('work_plan', models.TextField()),
            ],
            options={
                'verbose_name': 'Запись учета рабочего дня',
                'verbose_name_plural': 'Записи учета рабочего дня',
            },
        ),
    ]
