# Generated by Django 5.2.4 on 2025-07-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordworkday',
            options={'verbose_name': 'Запись учета рабочего дня', 'verbose_name_plural': 'Записи учета рабочего дня'},
        ),
    ]
