# Generated by Django 5.2.4 on 2025-07-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='machine',
            field=models.CharField(blank=True, max_length=50, verbose_name='Должность'),
        ),
    ]
